spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/data-jpa
    username: postgres
    password: 2004
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
